package com.workday.jersey;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.ResponseBuilder;

import org.glassfish.jersey.media.multipart.FormDataMultiPart;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.workday.jersey.initProcess.ServletContextClass;
import com.workday.jersey.validationProcessing.TransformationProcess;
 
/**
 * Text Schema Service provider for http requests
 * 
 * Input requirement: MediaType.MULTIPART_FORM_DATA
 * 		- field "inputFile", type File
 * 		- field "schemaFile", type File
 * 
 * Supported transformation:
 * 		-text file to xml.  
 * 		-xml file to text.  
 * 
 * 	url: /ValidateService/webapi/runSchema
 * 
 * Transformation processing error messages are generated by TextSchemaProcessor
 * 
 * @author Elisa Yan
 * @author Britney Wong
 * 
 * @since 9.2.2015
 */
@Path("/runSchema")
public class textSchemaService {

	final Logger logger = LoggerFactory.getLogger(textSchemaService.class);
	
	final int SUCCESS = 200;
	final int CLIENT_FAIL = 400;
	final int SERVER_ERROR = 500;
		
	/**
	 * Processes input and schema processing requests
	 * @param formParams FormDataMultipart object in the Request body
	 * @return Response with result as a formatted string
	 */
	@POST
	@Consumes(MediaType.MULTIPART_FORM_DATA)    
	@Produces(MediaType.TEXT_PLAIN)
	public Response processByFileName(FormDataMultiPart formParams) {
		int statusInt;
		String outputString;
		ResponseBuilder response;

		logger.info("parsing input multipart form");
		
		String inputFileName = formParams.getField("inputFile").getFormDataContentDisposition().getFileName();		
		InputStream inputIs = formParams.getField("inputFile").getValueAs(InputStream.class);
		String schemaSource = formParams.getField("schemaSource").getValueAs(String.class);
		logger.debug("schema source: " + schemaSource);
		InputStream schemaIs;

		if (schemaSource.toLowerCase().contains("svn")) {
			String schemaFileName = formParams.getField("schemaFileName").getValueAs(String.class);
			schemaIs = getInputStream(schemaFileName);
			logger.debug("SVN schema inputstream from " + schemaFileName);
		} else {
			schemaIs = formParams.getField("schemaFile").getValueAs(InputStream.class);
			logger.debug("Schema inputstream from file attachment in multipart form");
		}
		
		try{
			if (inputIs == null || schemaIs == null) {
				statusInt = CLIENT_FAIL;
				outputString = "Can't process input parameters";
				logger.error("can't read input and schema inputstream");
			} else if (inputFileName.endsWith(".txt")) {
				logger.trace("invoking textToXML");
				statusInt = SUCCESS;
				outputString = TransformationProcess.txtToXML(inputIs, schemaIs);
			} else if (inputFileName.endsWith(".xml")) {
				logger.trace("invoking xmlToText");
				statusInt = SUCCESS;
				outputString = TransformationProcess.xmlToText(inputIs, schemaIs);
			} else {
				statusInt = CLIENT_FAIL;
				outputString = "Invalid input for transformation.";
				logger.error("input fie is not .txt or .xml");
			}
			inputIs.close();

		} catch (Exception ex){
			statusInt = SERVER_ERROR;
			outputString = ex.getMessage();
			logger.error("text schema validation fail");
		}
		response = Response.status(statusInt).entity(outputString);
		
		//CORS HttpResponse header
		response.header("Access-Control-Allow-Origin", "*");
		response.header("Access-Control-Allow-Methods", "GET, POST, PUT, OPTIONS, X-XSRF-TOKEN");
		response.header("Access-Control-Allow-Headers", "Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With");
		
		//End of Header
	    return response.build();
	}
	
	public InputStream getInputStream(String fileName) {
//		ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
//		String schemasFolderPath = classLoader.getResource("scripts/svnFiles").getPath();
//		File schemaFile = new File(schemasFolderPath + fileName);
		File schemaFile = new File(ServletContextClass.getScriptsPath() + "svnFiles/" + fileName);
	    try {
	    	logger.debug("get " + fileName + " inputstream from svnFiles folder");
			return new FileInputStream(schemaFile);			
		} catch (FileNotFoundException e) {	
			logger.error(fileName + " not found");
			e.printStackTrace();
		}
		return null;
	}

}